apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-2
  labels:
    app: lab-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab-2
  template:
    metadata:
      labels:
        app: lab-2
    spec:
      containers:
      - name: lab-2
        image: ifilyaninitmo/itdt-contained-frontend:master
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_USERNAME
          value: student
        - name: REACT_APP_COMPANY_NAME
          value: ict_itmo  

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: lab-2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer              